### PR TITLE
Design review changes

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Fixed the design review comments.

## QA
- Pull down branch and run `gulp build`
- Open index.html
- Check that all the points in [the issue](https://github.com/canonical-webteam/global-nav/issues/26) have been addressed

## Details
Fixes https://github.com/canonical-webteam/global-nav/issues/26

## Screenshot
More link on a large screen:
canonical global navigation demo

### CODE REVIEW

**Comment by anthonydillon** [comment]
[[global-nav] Design review changes](https://trello.com/c/aHmrDIGH/3244-global-nav-design-review-changes)

**Comment by anthonydillon** [comment]
@yaili @joanasa89 For design reviews:
canonical global navigation demo 4
canonical global navigation demo 3
canonical global navigation demo 2

**Comment by grahambancroft** [comment]
Code and QA 👍

**Comment by yaili** [comment]
Can you tell me what the background colour is of the ubuntu websites link? It should be the same background colour as the other footer links (eg. Cloud, Desktop, etc.). The more bit looks OK.

**Comment by anthonydillon** [comment]
The color is the same as the global nav on large screens (#efefef).

**Comment by yaili** [comment]
On large screens it's #f7f7f7 though https://www.ubuntu.com/cloud

**Comment by anthonydillon** [comment]
Here is a demo of what is in master:
https://canonical-webteam.github.io/global-nav/

Is the background colour incorrect?

**Comment by yaili** [comment]
Yes, the colour on ubuntu.com is f7f7f7

**Comment by anthonydillon** [comment]
Done, demo here: https://anthonydillon.github.io/global-nav/

**Comment by yaili** [comment]
The background colour is still not right in small screens, it's too dark.

**Comment by anthonydillon** [comment]
@yaili updated the background colour on small screens

**Comment by yaili** [comment]
It's still the same colour when it's open…

**Comment by anthonydillon** [comment]
@yaili that is due to the focus state. We need a style for focus so it's accessible. @richmccartney what was your styling?

**Comment by richmccartney** [comment]
```scss
@mixin focus($color: $color-focus, $width: 1px, $offset: 2px) {
  &:focus,
  &:active {
    outline: $width solid $color;
    outline-offset: $offset;
  }
}
```

Hi @anthonydillon this is the mixin I have made for focus states, the focus colour is set to ```#19b6ee```. Hope this helps :)

**Comment by anthonydillon** [comment]
@richmccartney thanks, I'll apply and see what it looks like.

**Comment by richmccartney** [comment]
@anthonydillon you might need to tinker with the offset so it doesn't run out of bounds of the browser / screen :)

**Comment by anthonydillon** [comment]
@yaili Added the new focus styling so the background does not have to change now. What do you think? https://anthonydillon.github.io/global-nav/#global-nav

**Pull request merged**
