### PR TITLE
Make login menu optional

### PR DESCRIPTION
**Pull request by nottrobin**
Make it so `logins` and `products` can be set to `false` when calling `createNav`.

Fixes https://github.com/canonical-webteam/global-nav/issues/59

Bump version to `v1.2.0` for this change.

QA
--

``` bash
yarn install
yarn build
chromium-browser index.html  # Or otherwise open index.html in your browser
```

Check the nav works. Now, in index.html, try changing line 56 to:

``` html
<script>canonicalGlobalNav.createNav({showLogins: false});</script>
```

Refresh `index.html` in your browser and check the nav behaves as expected.

### CODE REVIEW

**Comment by tbille** [comment]
Set `logins` or `products` as `true` the global-nav doesn't shows up anymore:

`<script>canonicalGlobalNav.createNav({logins: true});</script>`

**Comment by nottrobin** [comment]
@tbille yes, it's not actually a Boolean. As mentioned in the README, it's of mixed-type. `products` is either an object or `false` (or anything "falsey"), `logins` is wither an array or something falsey.

I agree that it's potentially confusing to mix types like this, but also strict typing is not a be all and end all in a more dynamic language.

I personally am not crazy about duplication in an interface like: `{showLogins: true, logins: Array}`. It seems redundant.

In this case, I think it *would* make sense to simplify the interface to not allow overriding of `logins` at all, and so we could replace `logins` and `products` with `showLogins` and `showProducts`, which *would* be pure Booleans. But I was trying not to change the interface more than I needed to, for backwards compatibility. I'll ask @anthonydillon if this caution is needed to support current sites, or if currently everything is simply calling `createNav()` without any arguments.

**Comment by nottrobin** [comment]
> @tbille And it seems the file yarn.lock has been updated, could you add it to the PR?

I was tempted to push back on this as out-of-scope for this PR, since I didn't actually change any dependencies. But since I'm also proposing a new version of the module, it's probably best to update `yarn.lock` at the same time, so I'll do it. But it does kinda work against the mantra of PRs being as small as possible.

**Comment by nottrobin** [comment]
@tbille okay I discussed with @anthonydillon. You're definitely right, that is not a nice way to write it.

What I'd like to do is make the interface to that function much simpler, as:

```
createNav({maxWidth: '68em', showLogins: true})
```

Because @anthonydillon agreed that the other options shouldn't really be customised.

Does that sound good to you @tbille?

**Comment by nottrobin** [comment]
Okay @tbille, ready for re-review. I've fixed up the `createNav` interface and updated `yarn.lock`

**Pull request merged**
