### PR TITLE
Refactor the code base

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Updated the classes used to reflect BEM. Refactored the Sass to use an ITCSS structure.

## QA
- Pull this branch
- Run `make develop`
- Then open `index.html` in your browser
- Check the more menu opens

_No small screen styling yet. That is a follow-up_

## Details
Card: https://trello.com/c/BPDeQY7Z

### CODE REVIEW

**Comment by anthonydillon** [comment]
[Refactor global-nav project](https://trello.com/c/BPDeQY7Z/2976-refactor-global-nav-project)

**Comment by pmahnke** [comment]
I think your instructions are wrong.

1. npm install gulp
2. npm install
3. gulp build
4. open index.html

Also, the font-size is 12px, not 13px like on live, is that on purpose?

**Comment by anthonydillon** [comment]
Oh yes, you need to install the dependencies too. I should have written them. 

If they are 13 on live. Then they should be 13. I'll update that.

**Comment by anthonydillon** [comment]
@pmahnke Updated the font-size to `13px`. Ready for review again.

**Pull request merged**
